Car-Rental-Front-End: Car list page
wassimchakib/Car-Rental-Front-End pull request #25
Opened 2023-04-09 08:00 UTC by Profsain

## Summary

- Added Car list page

## Changes log

- [x] Installed React Pagination
- [x] Created Pagination
- [x]  Added car list card

## Acceptance criteria

- [x] The page should have title
- [x] The page should contain car_name, description, car_image
- [x] The page should allow user to move left or right
- [x] When user clicks on specific car, it should redirect to car detail page
- [x] .

2023-04-09 14:22 UTC, wassimchakib commented
Hi @Profsain,
# STATUS: INVALID REQUEST ❌ ❌ 
While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project that doesn't have a passed linters, please try to fix them 👍 👍 

Cheers and Happy coding!👏👏👏

2023-04-11 07:00 UTC, KIsmoilov requested changes
Hi @Profsain    , 

Although you made an effort to implement the requirements, you still need to fix several issues to proceed.

![almost4](https://user-images.githubusercontent.com/41912912/192947170-b3a5e934-2f1f-4bea-8dde-a6244a5aa7b9.gif)

 ## Highlights 💯 
- No linter errors. :heavy_check_mark:
- Git flow is followed. :heavy_check_mark:
- PR has a good title and summary. ✔️

 ## Required Changes ♻️
- As you can see in the screenshot that the pagination container does not have a nice design. 
- Please fix the width by changing it to 100%
- There should be consistency between the positions of page numbers.
- Please add some margin-top to the title of the page.

![Screen Shot 2023-04-11 at 11 23 13 AM (2)](https://user-images.githubusercontent.com/101260188/231077511-8980bf61-019a-4684-bc29-6399e2ac5eb4.png)

- As you can see in the screenshot when the user scrolls down the pagination container stays fixed in the middle of the screen, please fix it

![Screen Shot 2023-04-11 at 11 26 21 AM (2)](https://user-images.githubusercontent.com/101260188/231077521-42e3ac47-741c-43be-a3ef-1e638b926e98.png)

- The buttons in the pagination container are having an issue when hovered and clicked.  Please pay attention when the cursor is in the middle of the button it is clickable, but if you put the cursor a little bit closer to the border it is unclickable. So that the border and styling should have been implemented not on the `<li class="page-item>"`, but on the `<a class="page-link"`.

![Screen Shot 2023-04-11 at 11 36 05 AM (2)](https://user-images.githubusercontent.com/101260188/231077523-f7dcdbda-80ec-4435-8128-940506875307.png)






## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

2023-04-11 09:24 UTC, Profsain commented
Hi @KIsmoilov 
I have implemented all required changes. Kindly review my PR

2023-04-11 19:37 UTC, wassimchakib approved these changes
Hi @Profsain , 
I'm Wassim your reviewer for this PR. :wave: :wave: 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media3.giphy.com/media/YKdm91XONLTaw/giphy-downsized-medium.gif"/>

## Highlights
:heavy_check_mark: Followed GitFlow.
:heavy_check_mark: No linter errors.
:heavy_check_mark: Good PR summary.

## Optional suggestions
[OPTIONAL] N/A 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

2023-04-11 19:37 UTC, wassimchakib commented on src/components/cars-components/cars.js
> +export default items;
[Optional], Please try to delete this static JSON file in the future and use redux state

2023-04-11 19:37 UTC, wassimchakib commented on src/index.js
> +// import 'bootstrap/dist/css/bootstrap.min.css';
[Optional], Kindly delete the comment here

2023-04-11 19:39 UTC, merged